version: '2.4'
services:

  batch-process:
    build:
      context: .
      dockerfile: .
    container_name: batch-container
    env_file: .env
    environment:
      PROCESS: ${PROCESS}
    links:
      - "mysql:mysql"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:5.6.37
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "batch_example"
    volumes:
      - ./scripts/db-setup.sql:/docker-entrypoint-initdb.d/dp-setup.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3